# Generated by Django 4.2.2 on 2023-07-03 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subproject_sea', '0002_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='address',
        ),
    ]
