# Generated by Django 4.2.2 on 2023-07-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subproject_sea', '0004_remove_admin_id_remove_admin_user_admin_adminid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Studentphone',
            field=models.CharField(default=3, max_length=12),
            preserve_default=False,
        ),
    ]
